export 'package:componentes/screens/slider_screen.dart';
export 'package:componentes/screens/inputs_screen.dart';
export 'package:componentes/screens/animacion_screen.dart';
export 'package:componentes/screens/inicio_screen.dart';
export 'package:componentes/screens/listavista_screen.dart';
export 'package:componentes/screens/listavista_screen_original.dart';
export 'package:componentes/screens/alertas_screen.dart';
export 'package:componentes/screens/tarjetas_screen.dart';
export 'package:componentes/screens/avatar_screen.dart';
